name: Parse Issue Comments

on:
  issue_comment:
    types: [created]

jobs:
  respond-to-user:
    runs-on: ubuntu-latest
    steps:
    - name: Start Comment
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Thanks for the comment!  Checking in now...'
          })
  deploy-comment-dev:
    if: github.event.comment.body == '.deploy dev' || github.event.comment.body == '.deploy development'
    uses: ./.github/workflows/run-deploy.yml
    with:
      environment: development
  deploy-comment-staging:
    if: github.event.comment.body == '.deploy staging' || github.event.comment.body == '.deploy stage'
    uses: ./.github/workflows/run-deploy.yml
    with:
      environment: staging
  deploy-comment-prod:
    if: github.event.comment.body == '.deploy prod' || github.event.comment.body == '.deploy production'
    runs-on: ubuntu-latest
    steps:
      # Require approval from a code owner to deploy to production
      - name: Comment that approval is needed
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for the comment!  It looks like you are trying to deploy to production.  Please wait for a code owner to approve this request. @collinmcneese please approve'
            })
