name: Run Deployment

on:
  workflow_call:
    inputs:
      environment:
        description: |
          Environment(s) to deploy to.  This can be a single string or a comma separated list of environments.
        type: string
        required: true
      version:
        description: 'Version to deploy'
        type: string
        default: 'main'

jobs:
  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.environment, 'development') }}
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Run Deployment
        run: |
          echo "Deploying to Development"
      - name: Comment to issue when done
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: ${{ github.event.repository.owner.login }},
              repo: ${{ github.event.repository.name }},
              body: 'Deployment to Development is complete.'
            })

  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.environment, 'staging') }}
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Run Deployment
        run: |
          echo "Deploying to Staging"
      - name: Comment to issue when done
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: ${{ github.event.repository.owner.login }},
              repo: ${{ github.event.repository.name }},
              body: 'Deployment to Staging is complete.'
            })

  deploy-to-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.environment, 'production') }}
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Run Deployment
        run: |
          echo "Deploying to Production"
      - name: Comment to issue when done
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: ${{ github.event.repository.owner.login }},
              repo: ${{ github.event.repository.name }},
              body: 'Deployment to Production is complete.'
            })
