name: Run Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: |
          Environment(s) to deploy to.  This can be a single string or a comma separated list of environments.
        type: choice
        options:
          - development
          - staging
          - production
      version:
        description: 'Version to deploy'
        type: string
        default: 'main'

jobs:
  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.environment, 'development') }}
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Deployment
        run: |
          echo "Deploying to Development"

  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.environment, 'staging') }}
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Deployment
        run: |
          echo "Deploying to Staging"

  deploy-to-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ contains(inputs.environment, 'production') }}
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Deployment
        run: |
          echo "Deploying to Production"
